import 'package:flutter/widgets.dart';

class GigvoraLocalizations {
  GigvoraLocalizations(this.locale);

  final Locale locale;

  static const Locale defaultLocale = Locale('en');

  static const List<Locale> supportedLocales = <Locale>[
    Locale('en'),
    Locale('fr'),
    Locale('es'),
    Locale('pt'),
    Locale('it'),
    Locale('pl'),
    Locale('hi'),
    Locale('ar'),
    Locale('de'),
    Locale('ru'),
  ];

  static const Map<String, String> _nativeLanguageNames = <String, String>{
    'en': 'English',
    'fr': 'Français',
    'es': 'Español',
    'pt': 'Português',
    'it': 'Italiano',
    'pl': 'Polski',
    'hi': 'हिन्दी',
    'ar': 'العربية',
    'de': 'Deutsch',
    'ru': 'Русский',
  };

  static const Map<String, Map<String, String>> _localizedValues = <String, Map<String, String>>{
    'en': {
      'language.label': 'Language',
      'language.menuTitle': 'Choose your language',
      'language.ariaLabel': 'Change language',
      'navigation.feed': 'Live Feed',
      'navigation.explorer': 'Explorer',
      'navigation.jobs': 'Jobs',
      'navigation.gigs': 'Gigs',
      'navigation.projects': 'Projects',
      'navigation.launchpad': 'Launchpad',
      'navigation.volunteering': 'Volunteering',
      'navigation.groups': 'Groups',
      'navigation.pages': 'Pages',
      'navigation.mentors': 'Mentors',
      'navigation.inbox': 'Inbox',
      'navigation.security-operations': 'Security Ops',
      'navigation.profile': 'Profile',
      'menu.dashboard': 'Dashboard',
      'menu.profile': 'Profile',
      'menu.notifications': 'Notifications',
      'menu.messages': 'Messages',
      'menu.markAllRead': 'Mark all read',
      'menu.openNotificationCenter': 'Open notification centre',
      'menu.openInbox': 'Open inbox',
      'menu.financialHub': 'Financial hub',
      'menu.trustCenter': 'Trust centre',
      'menu.supportCenter': 'Support centre',
      'menu.securityOperations': 'Security operations',
      'menu.logout': 'Logout',
      'menu.requestAccess': 'Request access',
      'menu.manageMemberships': 'Manage memberships',
      'menu.contactSupport': 'Contact support',
      'auth.login': 'Login',
      'auth.register': 'Join Now',
      'auth.startProfile': 'Start your free profile',
      'auth.watchTour': 'Watch a 90-second walk-through',
      'hero.tagline': 'Gigvora platform',
      'hero.heading': 'Hire brilliantly. Collaborate beautifully.',
      'hero.subheading':
          'Gigvora pairs curated talent with effortless workflows so your team can launch ideas without the jargon and without the wait.',
      'hero.liveMoments': 'Live moments',
      'hero.liveMomentsDescription': 'Real teams shipping now',
      'hero.statusBadge': 'In sync',
      'hero.stats.teams': 'teams scaling global talent',
      'hero.stats.projects': 'projects delivered with heart',
      'hero.stats.onboarding': 'average onboarding time',
      'hero.deckSubtitle': 'Web and mobile dashboards stay perfectly in step.',
      'home.guestTitle': 'Gigvora home',
      'home.guestSubtitle': 'Sign in to unlock personalised dashboards',
      'home.guestDescription': 'Pick a path to join the network or return to your saved progress.',
      'home.guestLogin': 'Sign in to continue',
      'home.guestRegister': 'Create a Gigvora profile',
      'home.guestInfo':
          'Not sure where to start? Tap "Create a Gigvora profile" to explore freelancer, company, and agency onboarding.',
    },
    'fr': {
      'language.label': 'Langue',
      'language.menuTitle': 'Choisissez votre langue',
      'language.ariaLabel': 'Changer de langue',
      'navigation.feed': 'Fil en direct',
      'navigation.explorer': 'Explorateur',
      'navigation.jobs': 'Offres',
      'navigation.gigs': 'Missions',
      'navigation.projects': 'Projets',
      'navigation.launchpad': 'Plateforme de lancement',
      'navigation.volunteering': 'Bénévolat',
      'navigation.groups': 'Groupes',
      'navigation.pages': 'Pages',
      'navigation.mentors': 'Mentors',
      'navigation.inbox': 'Boîte de réception',
      'navigation.security-operations': 'Ops sécurité',
      'navigation.profile': 'Profil',
      'menu.dashboard': 'Tableau de bord',
      'menu.profile': 'Profil',
      'menu.notifications': 'Notifications',
      'menu.messages': 'Messages',
      'menu.markAllRead': 'Tout marquer comme lu',
      'menu.openNotificationCenter': 'Ouvrir le centre de notifications',
      'menu.openInbox': 'Ouvrir la boîte de réception',
      'menu.financialHub': 'Centre financier',
      'menu.trustCenter': 'Centre de confiance',
      'menu.supportCenter': "Centre d'assistance",
      'menu.securityOperations': 'Opérations de sécurité',
      'menu.logout': 'Déconnexion',
      'menu.requestAccess': "Demander l'accès",
      'menu.manageMemberships': 'Gérer les adhésions',
      'menu.contactSupport': 'Contacter le support',
      'auth.login': 'Connexion',
      'auth.register': 'Rejoindre maintenant',
      'auth.startProfile': 'Créer votre profil gratuit',
      'auth.watchTour': 'Regarder une présentation de 90 secondes',
      'hero.tagline': 'Plateforme Gigvora',
      'hero.heading': 'Recrutez brillamment. Collaborez avec élégance.',
      'hero.subheading':
          'Gigvora associe des talents sélectionnés à des flux de travail fluides pour que votre équipe lance des idées sans jargon ni attente.',
      'hero.liveMoments': 'Moments en direct',
      'hero.liveMomentsDescription': 'Équipes réelles en production',
      'hero.statusBadge': 'Synchronisé',
      'hero.stats.teams': 'équipes développant des talents mondiaux',
      'hero.stats.projects': 'projets livrés avec passion',
      'hero.stats.onboarding': "délai moyen d'intégration",
      'hero.deckSubtitle': 'Les tableaux de bord web et mobile restent parfaitement synchronisés.',
      'home.guestTitle': 'Accueil Gigvora',
      'home.guestSubtitle': 'Connectez-vous pour déverrouiller des tableaux de bord personnalisés',
      'home.guestDescription': 'Choisissez un parcours pour rejoindre le réseau ou revenir à votre progression enregistrée.',
      'home.guestLogin': 'Se connecter pour continuer',
      'home.guestRegister': 'Créer un profil Gigvora',
      'home.guestInfo':
          'Vous ne savez pas par où commencer ? Touchez « Créer un profil Gigvora » pour explorer les parcours indépendant, entreprise et agence.',
    },
    'es': {
      'language.label': 'Idioma',
      'language.menuTitle': 'Elige tu idioma',
      'language.ariaLabel': 'Cambiar idioma',
      'navigation.feed': 'Transmisión en vivo',
      'navigation.explorer': 'Explorador',
      'navigation.jobs': 'Empleos',
      'navigation.gigs': 'Trabajos',
      'navigation.projects': 'Proyectos',
      'navigation.launchpad': 'Plataforma de lanzamiento',
      'navigation.volunteering': 'Voluntariado',
      'navigation.groups': 'Grupos',
      'navigation.pages': 'Páginas',
      'navigation.mentors': 'Mentores',
      'navigation.inbox': 'Bandeja de entrada',
      'navigation.security-operations': 'Operaciones de seguridad',
      'navigation.profile': 'Perfil',
      'menu.dashboard': 'Panel',
      'menu.profile': 'Perfil',
      'menu.notifications': 'Notificaciones',
      'menu.messages': 'Mensajes',
      'menu.markAllRead': 'Marcar todo como leído',
      'menu.openNotificationCenter': 'Abrir centro de notificaciones',
      'menu.openInbox': 'Abrir bandeja de entrada',
      'menu.financialHub': 'Centro financiero',
      'menu.trustCenter': 'Centro de confianza',
      'menu.supportCenter': 'Centro de soporte',
      'menu.securityOperations': 'Operaciones de seguridad',
      'menu.logout': 'Cerrar sesión',
      'menu.requestAccess': 'Solicitar acceso',
      'menu.manageMemberships': 'Gestionar membresías',
      'menu.contactSupport': 'Contactar soporte',
      'auth.login': 'Iniciar sesión',
      'auth.register': 'Únete ahora',
      'auth.startProfile': 'Crea tu perfil gratis',
      'auth.watchTour': 'Ver recorrido de 90 segundos',
      'hero.tagline': 'Plataforma Gigvora',
      'hero.heading': 'Contrata con brillantez. Colabora con estilo.',
      'hero.subheading':
          'Gigvora conecta talento seleccionado con flujos de trabajo sin fricción para que tu equipo lance ideas sin jerga ni demoras.',
      'hero.liveMoments': 'Momentos en vivo',
      'hero.liveMomentsDescription': 'Equipos reales produciendo ahora',
      'hero.statusBadge': 'Sincronizado',
      'hero.stats.teams': 'equipos potenciando talento global',
      'hero.stats.projects': 'proyectos entregados con pasión',
      'hero.stats.onboarding': 'tiempo medio de incorporación',
      'hero.deckSubtitle': 'Los paneles web y móviles se mantienen perfectamente sincronizados.',
      'home.guestTitle': 'Inicio Gigvora',
      'home.guestSubtitle': 'Inicia sesión para desbloquear paneles personalizados',
      'home.guestDescription': 'Elige un camino para unirte a la red o retomar tu progreso guardado.',
      'home.guestLogin': 'Inicia sesión para continuar',
      'home.guestRegister': 'Crea un perfil Gigvora',
      'home.guestInfo':
          '¿No sabes por dónde empezar? Pulsa «Crear un perfil Gigvora» para explorar los recorridos de freelancer, empresa y agencia.',
    },
    'pt': {
      'language.label': 'Idioma',
      'language.menuTitle': 'Escolha seu idioma',
      'language.ariaLabel': 'Alterar idioma',
      'navigation.feed': 'Feed ao vivo',
      'navigation.explorer': 'Explorador',
      'navigation.jobs': 'Vagas',
      'navigation.gigs': 'Projetos',
      'navigation.projects': 'Projetos',
      'navigation.launchpad': 'Base de lançamento',
      'navigation.volunteering': 'Voluntariado',
      'navigation.groups': 'Grupos',
      'navigation.pages': 'Páginas',
      'navigation.mentors': 'Mentores',
      'navigation.inbox': 'Caixa de entrada',
      'navigation.security-operations': 'Operações de segurança',
      'navigation.profile': 'Perfil',
      'menu.dashboard': 'Painel',
      'menu.profile': 'Perfil',
      'menu.notifications': 'Notificações',
      'menu.messages': 'Mensagens',
      'menu.markAllRead': 'Marcar tudo como lido',
      'menu.openNotificationCenter': 'Abrir centro de notificações',
      'menu.openInbox': 'Abrir caixa de entrada',
      'menu.financialHub': 'Centro financeiro',
      'menu.trustCenter': 'Centro de confiança',
      'menu.supportCenter': 'Centro de suporte',
      'menu.securityOperations': 'Operações de segurança',
      'menu.logout': 'Sair',
      'menu.requestAccess': 'Solicitar acesso',
      'menu.manageMemberships': 'Gerenciar associações',
      'menu.contactSupport': 'Contatar suporte',
      'auth.login': 'Entrar',
      'auth.register': 'Junte-se agora',
      'auth.startProfile': 'Crie seu perfil gratuito',
      'auth.watchTour': 'Assistir apresentação de 90 segundos',
      'hero.tagline': 'Plataforma Gigvora',
      'hero.heading': 'Contrate com brilho. Colabore com beleza.',
      'hero.subheading':
          'A Gigvora conecta talentos selecionados a fluxos de trabalho sem atrito para que sua equipe lance ideias sem jargões e sem espera.',
      'hero.liveMoments': 'Momentos ao vivo',
      'hero.liveMomentsDescription': 'Equipes reais entregando agora',
      'hero.statusBadge': 'Sincronizado',
      'hero.stats.teams': 'equipes escalando talento global',
      'hero.stats.projects': 'projetos entregues com cuidado',
      'hero.stats.onboarding': 'tempo médio de integração',
      'hero.deckSubtitle': 'Os painéis web e mobile permanecem perfeitamente sincronizados.',
      'home.guestTitle': 'Início Gigvora',
      'home.guestSubtitle': 'Faça login para desbloquear painéis personalizados',
      'home.guestDescription': 'Escolha um caminho para entrar na rede ou retomar o seu progresso salvo.',
      'home.guestLogin': 'Entrar para continuar',
      'home.guestRegister': 'Criar um perfil Gigvora',
      'home.guestInfo':
          'Não sabe por onde começar? Toque em «Criar um perfil Gigvora» para explorar os fluxos de freelancer, empresa e agência.',
    },
    'it': {
      'language.label': 'Lingua',
      'language.menuTitle': 'Scegli la tua lingua',
      'language.ariaLabel': 'Cambia lingua',
      'navigation.feed': 'Feed live',
      'navigation.explorer': 'Esploratore',
      'navigation.jobs': 'Offerte',
      'navigation.gigs': 'Incarichi',
      'navigation.projects': 'Progetti',
      'navigation.launchpad': 'Piattaforma di lancio',
      'navigation.volunteering': 'Volontariato',
      'navigation.groups': 'Gruppi',
      'navigation.pages': 'Pagine',
      'navigation.mentors': 'Mentor',
      'navigation.inbox': 'Posta in arrivo',
      'navigation.security-operations': 'Operazioni di sicurezza',
      'navigation.profile': 'Profilo',
      'menu.dashboard': 'Cruscotto',
      'menu.profile': 'Profilo',
      'menu.notifications': 'Notifiche',
      'menu.messages': 'Messaggi',
      'menu.markAllRead': 'Segna tutto come letto',
      'menu.openNotificationCenter': 'Apri centro notifiche',
      'menu.openInbox': 'Apri posta in arrivo',
      'menu.financialHub': 'Hub finanziario',
      'menu.trustCenter': 'Centro fiducia',
      'menu.supportCenter': 'Centro assistenza',
      'menu.securityOperations': 'Operazioni di sicurezza',
      'menu.logout': 'Disconnetti',
      'menu.requestAccess': 'Richiedi accesso',
      'menu.manageMemberships': 'Gestisci iscrizioni',
      'menu.contactSupport': 'Contatta il supporto',
      'auth.login': 'Accedi',
      'auth.register': 'Unisciti ora',
      'auth.startProfile': 'Crea il tuo profilo gratuito',
      'auth.watchTour': 'Guarda il tour di 90 secondi',
      'hero.tagline': 'Piattaforma Gigvora',
      'hero.heading': 'Assumi con brillantezza. Collabora con stile.',
      'hero.subheading':
          'Gigvora abbina talenti selezionati a flussi di lavoro fluidi così il tuo team lancia idee senza gergo e senza attese.',
      'hero.liveMoments': 'Momenti live',
      'hero.liveMomentsDescription': "Team reali all'opera ora",
      'hero.statusBadge': 'Sincronizzato',
      'hero.stats.teams': 'team che scalano talenti globali',
      'hero.stats.projects': 'progetti consegnati con cura',
      'hero.stats.onboarding': 'tempo medio di onboarding',
      'hero.deckSubtitle': 'Le dashboard web e mobile restano perfettamente allineate.',
      'home.guestTitle': 'Home Gigvora',
      'home.guestSubtitle': 'Accedi per sbloccare dashboard personalizzate',
      'home.guestDescription': 'Scegli un percorso per unirti alla rete o riprendere i progressi salvati.',
      'home.guestLogin': 'Accedi per continuare',
      'home.guestRegister': 'Crea un profilo Gigvora',
      'home.guestInfo':
          'Non sai da dove iniziare? Tocca «Crea un profilo Gigvora» per esplorare i percorsi freelancer, azienda e agenzia.',
    },
    'pl': {
      'language.label': 'Język',
      'language.menuTitle': 'Wybierz swój język',
      'language.ariaLabel': 'Zmień język',
      'navigation.feed': 'Aktualności na żywo',
      'navigation.explorer': 'Eksplorator',
      'navigation.jobs': 'Oferty pracy',
      'navigation.gigs': 'Zlecenia',
      'navigation.projects': 'Projekty',
      'navigation.launchpad': 'Platforma startowa',
      'navigation.volunteering': 'Wolontariat',
      'navigation.groups': 'Grupy',
      'navigation.pages': 'Strony',
      'navigation.mentors': 'Mentorzy',
      'navigation.inbox': 'Skrzynka odbiorcza',
      'navigation.security-operations': 'Operacje bezpieczeństwa',
      'navigation.profile': 'Profil',
      'menu.dashboard': 'Panel',
      'menu.profile': 'Profil',
      'menu.notifications': 'Powiadomienia',
      'menu.messages': 'Wiadomości',
      'menu.markAllRead': 'Oznacz wszystko jako przeczytane',
      'menu.openNotificationCenter': 'Otwórz centrum powiadomień',
      'menu.openInbox': 'Otwórz skrzynkę odbiorczą',
      'menu.financialHub': 'Centrum finansowe',
      'menu.trustCenter': 'Centrum zaufania',
      'menu.supportCenter': 'Centrum wsparcia',
      'menu.securityOperations': 'Operacje bezpieczeństwa',
      'menu.logout': 'Wyloguj',
      'menu.requestAccess': 'Poproś o dostęp',
      'menu.manageMemberships': 'Zarządzaj członkostwami',
      'menu.contactSupport': 'Skontaktuj się ze wsparciem',
      'auth.login': 'Zaloguj się',
      'auth.register': 'Dołącz teraz',
      'auth.startProfile': 'Utwórz darmowy profil',
      'auth.watchTour': 'Obejrzyj 90-sekundowy przegląd',
      'hero.tagline': 'Platforma Gigvora',
      'hero.heading': 'Rekrutuj z klasą. Współpracuj pięknie.',
      'hero.subheading':
          'Gigvora łączy wyselekcjonowane talenty z płynnymi procesami, dzięki czemu Twój zespół uruchamia pomysły bez żargonu i zwłoki.',
      'hero.liveMoments': 'Wydarzenia na żywo',
      'hero.liveMomentsDescription': 'Prawdziwe zespoły działające teraz',
      'hero.statusBadge': 'Zsynchronizowano',
      'hero.stats.teams': 'zespoły rozwijające globalne talenty',
      'hero.stats.projects': 'projekty dostarczane z pasją',
      'hero.stats.onboarding': 'średni czas wdrożenia',
      'hero.deckSubtitle': 'Panele webowe i mobilne pozostają doskonale zsynchronizowane.',
      'home.guestTitle': 'Strona główna Gigvora',
      'home.guestSubtitle': 'Zaloguj się, aby odblokować spersonalizowane pulpity',
      'home.guestDescription': 'Wybierz ścieżkę, aby dołączyć do sieci lub wrócić do zapisanych postępów.',
      'home.guestLogin': 'Zaloguj się, aby kontynuować',
      'home.guestRegister': 'Utwórz profil Gigvora',
      'home.guestInfo':
          'Nie wiesz, od czego zacząć? Dotknij «Utwórz profil Gigvora», aby poznać ścieżki freelancera, firmy i agencji.',
    },
    'hi': {
      'language.label': 'भाषा',
      'language.menuTitle': 'अपनी भाषा चुनें',
      'language.ariaLabel': 'भाषा बदलें',
      'navigation.feed': 'लाइव फ़ीड',
      'navigation.explorer': 'एक्सप्लोरर',
      'navigation.jobs': 'नौकरियाँ',
      'navigation.gigs': 'गिग्स',
      'navigation.projects': 'प्रोजेक्ट्स',
      'navigation.launchpad': 'लॉन्चपैड',
      'navigation.volunteering': 'स्वयंसेवा',
      'navigation.groups': 'समूह',
      'navigation.pages': 'पृष्ठ',
      'navigation.mentors': 'मार्गदर्शक',
      'navigation.inbox': 'इनबॉक्स',
      'navigation.security-operations': 'सुरक्षा संचालन',
      'navigation.profile': 'प्रोफ़ाइल',
      'menu.dashboard': 'डैशबोर्ड',
      'menu.profile': 'प्रोफ़ाइल',
      'menu.notifications': 'सूचनाएँ',
      'menu.messages': 'संदेश',
      'menu.markAllRead': 'सभी को पढ़ा चिह्नित करें',
      'menu.openNotificationCenter': 'सूचना केंद्र खोलें',
      'menu.openInbox': 'इनबॉक्स खोलें',
      'menu.financialHub': 'वित्तीय हब',
      'menu.trustCenter': 'ट्रस्ट सेंटर',
      'menu.supportCenter': 'सहायता केंद्र',
      'menu.securityOperations': 'सुरक्षा संचालन',
      'menu.logout': 'लॉगआउट',
      'menu.requestAccess': 'पहुंच का अनुरोध करें',
      'menu.manageMemberships': 'सदस्यता प्रबंधित करें',
      'menu.contactSupport': 'सपोर्ट से संपर्क करें',
      'auth.login': 'लॉगिन',
      'auth.register': 'अभी शामिल हों',
      'auth.startProfile': 'अपना निःशुल्क प्रोफ़ाइल शुरू करें',
      'auth.watchTour': '90 सेकंड का वॉक-थ्रू देखें',
      'hero.tagline': 'गिगवोरा प्लेटफ़ॉर्म',
      'hero.heading': 'बेहतर भर्ती करें। सुंदर सहयोग करें।',
      'hero.subheading':
          'गिगवोरा चुने हुए टैलेंट को सहज वर्कफ़्लो से जोड़ता है ताकि आपकी टीम बिना जटिल शब्दों और बिना इंतज़ार के विचार लॉन्च कर सके।',
      'hero.liveMoments': 'लाइव क्षण',
      'hero.liveMomentsDescription': 'अभी डिलीवर करते वास्तविक टीमें',
      'hero.statusBadge': 'समन्वय में',
      'hero.stats.teams': 'वैश्विक टैलेंट को स्केल करने वाली टीमें',
      'hero.stats.projects': 'जुनून से डिलीवर किए गए प्रोजेक्ट्स',
      'hero.stats.onboarding': 'औसत ऑनबोर्डिंग समय',
      'hero.deckSubtitle': 'वेब और मोबाइल डैशबोर्ड पूरी तरह समन्वित रहते हैं।',
      'home.guestTitle': 'गिगवोरा होम',
      'home.guestSubtitle': 'व्यक्तिगत डैशबोर्ड अनलॉक करने के लिए साइन इन करें',
      'home.guestDescription': 'नेटवर्क से जुड़ने या अपने सहेजे हुए प्रगति पर लौटने के लिए एक रास्ता चुनें।',
      'home.guestLogin': 'जारी रखने के लिए साइन इन करें',
      'home.guestRegister': 'गिगवोरा प्रोफ़ाइल बनाएँ',
      'home.guestInfo':
          'समझ नहीं आ रहा कहाँ से शुरू करें? फ़्रीलांसर, कंपनी और एजेंसी ऑनबोर्डिंग देखने के लिए "गिगवोरा प्रोफ़ाइल बनाएँ" टैप करें।',
    },
    'ar': {
      'language.label': 'اللغة',
      'language.menuTitle': 'اختر لغتك',
      'language.ariaLabel': 'تغيير اللغة',
      'navigation.feed': 'البث المباشر',
      'navigation.explorer': 'المستكشف',
      'navigation.jobs': 'الوظائف',
      'navigation.gigs': 'العقود',
      'navigation.projects': 'المشروعات',
      'navigation.launchpad': 'منصة الإطلاق',
      'navigation.volunteering': 'التطوع',
      'navigation.groups': 'المجموعات',
      'navigation.pages': 'الصفحات',
      'navigation.mentors': 'المرشدون',
      'navigation.inbox': 'صندوق الوارد',
      'navigation.security-operations': 'عمليات الأمان',
      'navigation.profile': 'الملف الشخصي',
      'menu.dashboard': 'لوحة التحكم',
      'menu.profile': 'الملف الشخصي',
      'menu.notifications': 'الإشعارات',
      'menu.messages': 'الرسائل',
      'menu.markAllRead': 'تحديد الكل كمقروء',
      'menu.openNotificationCenter': 'فتح مركز الإشعارات',
      'menu.openInbox': 'فتح صندوق الوارد',
      'menu.financialHub': 'المركز المالي',
      'menu.trustCenter': 'مركز الثقة',
      'menu.supportCenter': 'مركز الدعم',
      'menu.securityOperations': 'عمليات الأمان',
      'menu.logout': 'تسجيل الخروج',
      'menu.requestAccess': 'طلب صلاحية',
      'menu.manageMemberships': 'إدارة العضويات',
      'menu.contactSupport': 'التواصل مع الدعم',
      'auth.login': 'تسجيل الدخول',
      'auth.register': 'انضم الآن',
      'auth.startProfile': 'ابدأ ملفك الشخصي مجانًا',
      'auth.watchTour': 'شاهد جولة مدتها 90 ثانية',
      'hero.tagline': 'منصة جيجفورا',
      'hero.heading': 'وظّف بامتياز. وتعاون بروعة.',
      'hero.subheading':
          'تربط جيجفورا المواهب المختارة بتدفقات عمل سلسة حتى يطلق فريقك الأفكار دون تعقيد أو انتظار.',
      'hero.liveMoments': 'لحظات مباشرة',
      'hero.liveMomentsDescription': 'فرق حقيقية تعمل الآن',
      'hero.statusBadge': 'متزامن',
      'hero.stats.teams': 'فرق تطور المواهب العالمية',
      'hero.stats.projects': 'مشروعات تُسلَّم بشغف',
      'hero.stats.onboarding': 'متوسط زمن الانضمام',
      'hero.deckSubtitle': 'تظل لوحات التحكم على الويب والهاتف متناسقة تمامًا.',
      'home.guestTitle': 'الصفحة الرئيسية لجيجفورا',
      'home.guestSubtitle': 'سجّل الدخول لفتح لوحات تحكم مخصصة',
      'home.guestDescription': 'اختر مسارك للانضمام إلى الشبكة أو العودة لتقدمك المحفوظ.',
      'home.guestLogin': 'سجّل الدخول للمتابعة',
      'home.guestRegister': 'أنشئ ملف جيجفورا',
      'home.guestInfo':
          'لا تعرف من أين تبدأ؟ اضغط «أنشئ ملف جيجفورا» لاستكشاف مسارات المستقلين والشركات والوكالات.',
    },
    'de': {
      'language.label': 'Sprache',
      'language.menuTitle': 'Wähle deine Sprache',
      'language.ariaLabel': 'Sprache ändern',
      'navigation.feed': 'Live-Feed',
      'navigation.explorer': 'Explorer',
      'navigation.jobs': 'Jobs',
      'navigation.gigs': 'Aufträge',
      'navigation.projects': 'Projekte',
      'navigation.launchpad': 'Launchpad',
      'navigation.volunteering': 'Ehrenamt',
      'navigation.groups': 'Gruppen',
      'navigation.pages': 'Seiten',
      'navigation.mentors': 'Mentoren',
      'navigation.inbox': 'Posteingang',
      'navigation.security-operations': 'Sicherheitsbetrieb',
      'navigation.profile': 'Profil',
      'menu.dashboard': 'Dashboard',
      'menu.profile': 'Profil',
      'menu.notifications': 'Benachrichtigungen',
      'menu.messages': 'Nachrichten',
      'menu.markAllRead': 'Alle als gelesen markieren',
      'menu.openNotificationCenter': 'Benachrichtigungscenter öffnen',
      'menu.openInbox': 'Posteingang öffnen',
      'menu.financialHub': 'Finanzhub',
      'menu.trustCenter': 'Trust Center',
      'menu.supportCenter': 'Support-Center',
      'menu.securityOperations': 'Sicherheitsbetrieb',
      'menu.logout': 'Abmelden',
      'menu.requestAccess': 'Zugriff anfordern',
      'menu.manageMemberships': 'Mitgliedschaften verwalten',
      'menu.contactSupport': 'Support kontaktieren',
      'auth.login': 'Anmelden',
      'auth.register': 'Jetzt beitreten',
      'auth.startProfile': 'Starte dein kostenloses Profil',
      'auth.watchTour': '90-Sekunden-Tour ansehen',
      'hero.tagline': 'Gigvora-Plattform',
      'hero.heading': 'Brillant einstellen. Stilvoll zusammenarbeiten.',
      'hero.subheading':
          'Gigvora verbindet kuratiertes Talent mit reibungslosen Workflows, damit dein Team Ideen ohne Jargon und ohne Warten starten kann.',
      'hero.liveMoments': 'Live-Momente',
      'hero.liveMomentsDescription': 'Echte Teams liefern jetzt',
      'hero.statusBadge': 'Synchron',
      'hero.stats.teams': 'Teams, die globale Talente skalieren',
      'hero.stats.projects': 'Projekte mit Herz geliefert',
      'hero.stats.onboarding': 'durchschnittliche Onboarding-Zeit',
      'hero.deckSubtitle': 'Web- und Mobile-Dashboards bleiben perfekt abgestimmt.',
      'home.guestTitle': 'Gigvora-Startseite',
      'home.guestSubtitle': 'Melde dich an, um personalisierte Dashboards freizuschalten',
      'home.guestDescription': 'Wähle einen Weg, um dem Netzwerk beizutreten oder zu deinem gespeicherten Fortschritt zurückzukehren.',
      'home.guestLogin': 'Zum Fortfahren anmelden',
      'home.guestRegister': 'Gigvora-Profil erstellen',
      'home.guestInfo':
          'Du weißt nicht, wo du anfangen sollst? Tippe auf «Gigvora-Profil erstellen», um Freelancer-, Unternehmens- und Agentur-Workflows zu entdecken.',
    },
    'ru': {
      'language.label': 'Язык',
      'language.menuTitle': 'Выберите язык',
      'language.ariaLabel': 'Сменить язык',
      'navigation.feed': 'Живая лента',
      'navigation.explorer': 'Обозреватель',
      'navigation.jobs': 'Вакансии',
      'navigation.gigs': 'Проекты',
      'navigation.projects': 'Проекты',
      'navigation.launchpad': 'Стартовая площадка',
      'navigation.volunteering': 'Волонтёрство',
      'navigation.groups': 'Группы',
      'navigation.pages': 'Страницы',
      'navigation.mentors': 'Наставники',
      'navigation.inbox': 'Входящие',
      'navigation.security-operations': 'Операции безопасности',
      'navigation.profile': 'Профиль',
      'menu.dashboard': 'Панель',
      'menu.profile': 'Профиль',
      'menu.notifications': 'Уведомления',
      'menu.messages': 'Сообщения',
      'menu.markAllRead': 'Отметить всё как прочитанное',
      'menu.openNotificationCenter': 'Открыть центр уведомлений',
      'menu.openInbox': 'Открыть входящие',
      'menu.financialHub': 'Финансовый центр',
      'menu.trustCenter': 'Центр доверия',
      'menu.supportCenter': 'Служба поддержки',
      'menu.securityOperations': 'Операции безопасности',
      'menu.logout': 'Выйти',
      'menu.requestAccess': 'Запросить доступ',
      'menu.manageMemberships': 'Управлять членствами',
      'menu.contactSupport': 'Связаться с поддержкой',
      'auth.login': 'Войти',
      'auth.register': 'Присоединиться',
      'auth.startProfile': 'Создайте бесплатный профиль',
      'auth.watchTour': 'Посмотреть 90-секундный обзор',
      'hero.tagline': 'Платформа Gigvora',
      'hero.heading': 'Нанимайте блестяще. Сотрудничайте красиво.',
      'hero.subheading':
          'Gigvora объединяет отобранные таланты с безупречными процессами, чтобы ваша команда запускала идеи без лишнего жаргона и задержек.',
      'hero.liveMoments': 'Моменты в прямом эфире',
      'hero.liveMomentsDescription': 'Реальные команды работают сейчас',
      'hero.statusBadge': 'Синхронизировано',
      'hero.stats.teams': 'команды, развивающие глобальные таланты',
      'hero.stats.projects': 'проекты, выполненные с душой',
      'hero.stats.onboarding': 'среднее время адаптации',
      'hero.deckSubtitle': 'Веб- и мобильные панели остаются идеально синхронизированными.',
      'home.guestTitle': 'Домашняя страница Gigvora',
      'home.guestSubtitle': 'Войдите, чтобы открыть персональные панели',
      'home.guestDescription': 'Выберите путь, чтобы присоединиться к сети или вернуться к сохранённому прогрессу.',
      'home.guestLogin': 'Войдите, чтобы продолжить',
      'home.guestRegister': 'Создать профиль Gigvora',
      'home.guestInfo':
          'Не знаете, с чего начать? Нажмите «Создать профиль Gigvora», чтобы изучить пути фрилансера, компании и агентства.',
    },
  };

  static GigvoraLocalizations of(BuildContext context) {
    final localizations = maybeOf(context);
    assert(localizations != null, 'GigvoraLocalizations not found in context');
    return localizations!;
  }

  static GigvoraLocalizations? maybeOf(BuildContext context) {
    return Localizations.of<GigvoraLocalizations>(context, GigvoraLocalizations);
  }

  static Locale resolveLocales(List<Locale> locales) {
    for (final locale in locales) {
      final resolved = supportedLocaleFromCode(locale.languageCode);
      if (resolved != null) {
        return resolved;
      }
    }
    return defaultLocale;
  }

  static Locale? supportedLocaleFromCode(String? code) {
    if (code == null || code.isEmpty) {
      return null;
    }
    final normalized = code.toLowerCase();
    for (final locale in supportedLocales) {
      if (locale.languageCode == normalized) {
        return locale;
      }
    }
    return null;
  }

  static String nativeName(String code) => _nativeLanguageNames[code] ?? code.toUpperCase();

  String translate(String key, {String? fallback}) {
    final languageMap = _localizedValues[locale.languageCode] ?? _localizedValues[defaultLocale.languageCode]!;
    final defaultMap = _localizedValues[defaultLocale.languageCode]!;
    if (languageMap.containsKey(key)) {
      return languageMap[key]!;
    }
    if (locale.languageCode != defaultLocale.languageCode && defaultMap.containsKey(key)) {
      return defaultMap[key]!;
    }
    return fallback ?? key;
  }

  static const LocalizationsDelegate<GigvoraLocalizations> delegate = _GigvoraLocalizationsDelegate();
}

class _GigvoraLocalizationsDelegate extends LocalizationsDelegate<GigvoraLocalizations> {
  const _GigvoraLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return GigvoraLocalizations.supportedLocaleFromCode(locale.languageCode) != null;
  }

  @override
  Future<GigvoraLocalizations> load(Locale locale) async {
    return GigvoraLocalizations(GigvoraLocalizations.supportedLocaleFromCode(locale.languageCode) ?? GigvoraLocalizations.defaultLocale);
  }

  @override
  bool shouldReload(_GigvoraLocalizationsDelegate old) => false;
}
