export const testimonials = {
  hero: {
    eyebrow: 'Social proof',
    heading: 'Trusted by the operators shipping the future',
    description:
      'Gigvora crews orchestrate launches for venture studios, enterprise programmes, and impact missions with the polish of tier-one networks.',
    stats: [
      { value: '68', label: 'NPS', helper: 'Rolling 90-day sentiment' },
      { value: '4,200+', label: 'Crews', helper: 'Programmes delivered globally' },
      { value: '92%', label: 'Renewals', helper: 'Expansions within 60 days' },
    ],
    logos: ['Northwind Digital', 'Forma Studio', 'Atlas Labs', 'Redbird Ventures', 'Aurora Collective'],
  },
  items: [
    {
      id: 'northwind',
      quote:
        'Gigvora unlocked a vetted product pod in 48 hours—finance, compliance, and delivery were already aligned.',
      name: 'Leah Patel',
      authorName: 'Leah Patel',
      role: 'VP Operations',
      authorRole: 'VP Operations',
      company: 'Northwind Labs',
      authorCompany: 'Northwind Labs',
      highlight: 'Scaled seven markets without adding ops headcount.',
      avatar: 'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&w=128&q=80',
      avatarUrl: 'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&w=128&q=80',
      avatarAlt: 'Portrait of Leah Patel smiling',
      badge: 'Enterprise rollout',
    },
    {
      id: 'forma-studio',
      quote:
        'We replaced scattered contractors with a dedicated Gigvora crew. The quality is exceptional and the admin load disappeared overnight.',
      name: 'Ivy Chen',
      authorName: 'Ivy Chen',
      role: 'Founder',
      authorRole: 'Founder',
      company: 'Forma Studio',
      authorCompany: 'Forma Studio',
      highlight: 'Closed enterprise deals with on-demand specialists.',
      avatar: 'https://images.unsplash.com/photo-1502685104226-ee32379fefbe?auto=format&fit=crop&w=128&q=80',
      avatarUrl: 'https://images.unsplash.com/photo-1502685104226-ee32379fefbe?auto=format&fit=crop&w=128&q=80',
      avatarAlt: 'Portrait of Ivy Chen wearing a blazer',
      badge: 'Venture studio',
    },
    {
      id: 'aurora-collective',
      quote:
        'Our accelerator pairs mentors and founders instantly. The shared telemetry keeps every stakeholder on the same narrative, and the polish rivals the biggest professional networks.',
      name: 'Diego Martínez',
      authorName: 'Diego Martínez',
      role: 'Programme Director',
      authorRole: 'Programme Director',
      company: 'Aurora Collective',
      authorCompany: 'Aurora Collective',
      highlight: 'Raised cohort satisfaction to 96% in two seasons.',
      avatar: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=128&q=80',
      avatarUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=128&q=80',
      avatarAlt: 'Portrait of Diego Martínez laughing',
      badge: 'Global accelerator',
    },
    {
      id: 'redbird-ventures',
      quote:
        'Payments, compliance, and onboarding just work. Gigvora’s crews collaborate like an in-house team, and our partners comment on the polish every single review.',
      name: 'Amina Farouk',
      authorName: 'Amina Farouk',
      role: 'COO',
      authorRole: 'COO',
      company: 'Redbird Ventures',
      authorCompany: 'Redbird Ventures',
      highlight: 'Reduced vendor onboarding time by 63%.',
      avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=128&q=80',
      avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=128&q=80',
      avatarAlt: 'Portrait of Amina Farouk wearing glasses',
      badge: 'Funds & operations',
    },
    {
      id: 'civic-leap',
      quote:
        'The mentoring suite elevated our entire workforce programme. Cohorts rave about the experience because everything feels intentional, from storytelling to analytics.',
      name: 'Lena Patel',
      authorName: 'Lena Patel',
      role: 'Director of Workforce Innovation',
      authorRole: 'Director of Workforce Innovation',
      company: 'Civic Leap',
      authorCompany: 'Civic Leap',
      highlight: 'Graduation rates jumped 28% in one quarter.',
      avatar: 'https://images.unsplash.com/photo-1544723795-3fb6f89f5b39?auto=format&fit=crop&w=128&q=80',
      avatarUrl: 'https://images.unsplash.com/photo-1544723795-3fb6f89f5b39?auto=format&fit=crop&w=128&q=80',
      avatarAlt: 'Portrait of Lena Patel in a studio setting',
      badge: 'Impact programmes',
    },
  ],
};

export const joinCommunityCta = {
  eyebrow: 'Membership',
  title: 'Join the community where elite crews, mentors, and operators ship together',
  description:
    'Onboard in minutes, align collaborators, and access vetted specialists who move at the pace of your programme.',
  primaryAction: { label: 'Claim your seat', to: '/register' },
  secondaryAction: { label: 'Talk with our team', href: 'mailto:hello@gigvora.com' },
  supportingPoints: [
    'Curated crews that stay in sync with your roadmap',
    'Mentorship from seasoned operators and advisors',
    'Enterprise compliance, payments, and onboarding built-in',
    {
      title: 'Global reach with local nuance',
      description: '42 countries represented across product, growth, and impact missions.',
    },
  ],
  stats: [
    { label: 'Teams onboarded', value: '3,800+', helper: 'Accelerating launches worldwide' },
    { label: 'Average go-live', value: '6 weeks', helper: 'From kickoff to first delivery' },
    { label: 'Mentor network', value: '420+', helper: 'Operators coaching every cohort' },
  ],
  logos: ['Northwind Digital', 'Forma Studio', 'Atlas Labs', 'Redbird Ventures'],
  guarantees: ['SOC2 Type II', { label: 'Global compliance' }, { label: 'Escrow protected' }],
  testimonial: {
    quote: 'Gigvora aligned our mentors and operators within days—we shipped our launch playbook 3x faster.',
    name: 'Leah Patel',
    role: 'Programme Director',
    company: 'Northwind Digital',
    avatar: {
      src: 'https://cdn.gigvora.com/assets/avatars/leah-patel.png',
      alt: 'Portrait of Leah Patel smiling',
    },
  },
  footnote: 'Backed by production telemetry across venture, enterprise, and social impact programmes.',
};
