export const testimonials = [
  {
    quote:
      'Gigvora gave us a professional community that feels bespoke—every contributor arrived ready, every milestone was tracked, and our stakeholders finally have clarity.',
    name: 'Morgan Wells',
    authorName: 'Morgan Wells',
    role: 'VP People',
    authorRole: 'VP People',
    company: 'Northwind Digital',
    authorCompany: 'Northwind Digital',
    highlight: 'Scaled 7 markets without adding ops headcount.',
    avatar: 'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&w=128&q=80',
    avatarAlt: 'Portrait of Morgan Wells smiling',
    badge: 'Enterprise rollout',
  },
  {
    quote:
      'We replaced scattered contractors with a dedicated Gigvora crew. The quality is exceptional and the admin load disappeared overnight.',
    name: 'Ivy Chen',
    authorName: 'Ivy Chen',
    role: 'Founder',
    authorRole: 'Founder',
    company: 'Forma Studio',
    authorCompany: 'Forma Studio',
    highlight: 'Closed enterprise deals with on-demand specialists.',
    avatar: 'https://images.unsplash.com/photo-1502685104226-ee32379fefbe?auto=format&fit=crop&w=128&q=80',
    avatarAlt: 'Portrait of Ivy Chen wearing a blazer',
    badge: 'Venture studio',
  },
  {
    quote:
      'Our accelerator pairs mentors and founders instantly. The shared telemetry keeps every stakeholder on the same narrative, and the polish rivals the biggest professional networks.',
    name: 'Diego Martínez',
    authorName: 'Diego Martínez',
    role: 'Programme Director',
    authorRole: 'Programme Director',
    company: 'Aurora Collective',
    authorCompany: 'Aurora Collective',
    highlight: 'Raised cohort satisfaction to 96% in two seasons.',
    avatar: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=128&q=80',
    avatarAlt: 'Portrait of Diego Martínez laughing',
    badge: 'Global accelerator',
  },
  {
    quote:
      'Payments, compliance, and onboarding just work. Gigvora’s crews collaborate like an in-house team, and our partners comment on the polish every single review.',
    name: 'Amina Farouk',
    authorName: 'Amina Farouk',
    role: 'COO',
    authorRole: 'COO',
    company: 'Redbird Ventures',
    authorCompany: 'Redbird Ventures',
    highlight: 'Reduced vendor onboarding time by 63%.',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=128&q=80',
    avatarAlt: 'Portrait of Amina Farouk wearing glasses',
    badge: 'Funds & operations',
  },
  {
    quote:
      'The mentoring suite elevated our entire workforce programme. Cohorts rave about the experience because everything feels intentional, from storytelling to analytics.',
    name: 'Lena Patel',
    authorName: 'Lena Patel',
    role: 'Director of Workforce Innovation',
    authorRole: 'Director of Workforce Innovation',
    company: 'Civic Leap',
    authorCompany: 'Civic Leap',
    highlight: 'Graduation rates jumped 28% in one quarter.',
    avatar: 'https://images.unsplash.com/photo-1544723795-3fb6f89f5b39?auto=format&fit=crop&w=128&q=80',
    avatarAlt: 'Portrait of Lena Patel in a studio setting',
    badge: 'Impact programmes',
  },
];
