import { useFreelancerTimeline, computeTimelineAnalyticsFromClient } from './useFreelancerTimeline.js';
import {
  fetchUserTimelineWorkspace,
  updateUserTimelineSettings,
  createUserTimelineEntry,
  updateUserTimelineEntry,
  deleteUserTimelineEntry,
  createUserTimelinePost,
  updateUserTimelinePost,
  deleteUserTimelinePost,
  publishUserTimelinePost,
  recordUserTimelinePostMetrics,
} from '../services/userTimeline.js';

const USER_FALLBACK_WORKSPACE = {
  id: 'demo-client-workspace',
  userId: 'demo-client',
  timezone: 'UTC',
  defaultVisibility: 'connections',
  autoShareToFeed: false,
  reviewBeforePublish: true,
  distributionChannels: ['client portal', 'email'],
  contentThemes: ['delivery updates', 'milestones'],
  pinnedCampaigns: ['Q2 onboarding'],
  cadenceGoal: 2,
  lastSyncedAt: null,
  createdAt: null,
  updatedAt: null,
};

const USER_FALLBACK_POSTS = [
  {
    id: 'demo-client-post-1',
    userId: 'demo-client',
    workspaceId: 'demo-client-workspace',
    title: 'Sprint 5 delivery update',
    summary: 'Launched analytics dashboard and trained power users across the region.',
    content:
      'New dashboards are live with usage tracking enabled. Customer training sessions completed with 24 attendees.',
    status: 'published',
    visibility: 'connections',
    scheduledAt: null,
    publishedAt: '2024-04-08T09:30:00Z',
    timezone: 'UTC',
    heroImageUrl: null,
    allowComments: true,
    tags: ['delivery', 'analytics'],
    attachments: [
      {
        label: 'Launch deck',
        url: 'https://assets.gigvora.test/demos/client-launch.pdf',
        type: 'document',
        thumbnail: null,
      },
    ],
    targetAudience: [
      { label: 'Stakeholders', id: 'stakeholders' },
      { label: 'Executives', id: 'executives' },
    ],
    campaign: 'Transformation programme',
    callToAction: { label: 'View release notes', url: 'https://gigvora.test/releases' },
    metrics: {
      totals: {
        impressions: 820,
        views: 610,
        clicks: 74,
        comments: 12,
        reactions: 68,
        saves: 8,
        shares: 5,
        profileVisits: 24,
        leads: 3,
      },
      trend: [
        { capturedAt: '2024-04-07', impressions: 420, clicks: 32, reactions: 28, comments: 4, saves: 3, shares: 1 },
        { capturedAt: '2024-04-08', impressions: 400, clicks: 42, reactions: 40, comments: 8, saves: 5, shares: 4 },
      ],
    },
    linkedEntryCount: 1,
    createdAt: '2024-04-06T11:00:00Z',
    updatedAt: '2024-04-08T11:45:00Z',
  },
  {
    id: 'demo-client-post-2',
    userId: 'demo-client',
    workspaceId: 'demo-client-workspace',
    title: 'Upcoming onboarding wave',
    summary: 'Coordinating go-live support with legal and finance sign-off in progress.',
    content:
      'We are finalising the contract package and preparing training materials for the May customer onboarding wave.',
    status: 'scheduled',
    visibility: 'connections',
    scheduledAt: '2024-04-18T15:00:00Z',
    publishedAt: null,
    timezone: 'UTC',
    heroImageUrl: null,
    allowComments: true,
    tags: ['onboarding', 'planning'],
    attachments: [],
    targetAudience: [{ label: 'Program sponsors', id: 'sponsors' }],
    campaign: 'Customer success rollout',
    callToAction: { label: 'Review checklist', url: 'https://gigvora.test/onboarding-checklist' },
    metrics: {
      totals: {
        impressions: 260,
        views: 180,
        clicks: 18,
        comments: 3,
        reactions: 20,
        saves: 4,
        shares: 2,
        profileVisits: 9,
        leads: 1,
      },
      trend: [
        { capturedAt: '2024-04-15', impressions: 120, clicks: 7, reactions: 8, comments: 1, saves: 1, shares: 1 },
        { capturedAt: '2024-04-16', impressions: 140, clicks: 11, reactions: 12, comments: 2, saves: 3, shares: 1 },
      ],
    },
    linkedEntryCount: 1,
    createdAt: '2024-04-14T10:15:00Z',
    updatedAt: '2024-04-15T08:40:00Z',
  },
];

const USER_FALLBACK_ENTRIES = [
  {
    id: 'demo-client-entry-1',
    userId: 'demo-client',
    workspaceId: 'demo-client-workspace',
    title: 'Executive status review',
    description: 'Compile programme scorecard, budget deltas, and risk log for the steering committee.',
    entryType: 'milestone',
    status: 'in_progress',
    startAt: '2024-04-05T13:00:00Z',
    endAt: '2024-04-05T14:30:00Z',
    linkedPostId: 'demo-client-post-1',
    owner: 'Jordan Blake',
    channel: 'Teams',
    location: 'Virtual',
    tags: ['governance', 'reporting'],
    metadata: { checklist: ['Update KPI dashboard', 'Capture risks', 'Confirm attendees'] },
    linkedPost: {
      id: 'demo-client-post-1',
      title: 'Sprint 5 delivery update',
      status: 'published',
      visibility: 'connections',
      scheduledAt: null,
      publishedAt: '2024-04-08T09:30:00Z',
    },
    createdAt: '2024-04-03T09:00:00Z',
    updatedAt: '2024-04-04T12:15:00Z',
  },
  {
    id: 'demo-client-entry-2',
    userId: 'demo-client',
    workspaceId: 'demo-client-workspace',
    title: 'Customer onboarding rehearsal',
    description: 'Dry-run the onboarding script with operations and success teams.',
    entryType: 'event',
    status: 'planned',
    startAt: '2024-04-17T16:00:00Z',
    endAt: '2024-04-17T17:00:00Z',
    linkedPostId: 'demo-client-post-2',
    owner: 'Jordan Blake',
    channel: 'Zoom',
    location: 'Remote',
    tags: ['training', 'enablement'],
    metadata: { agenda: ['Run script', 'Collect feedback', 'Update checklist'] },
    linkedPost: {
      id: 'demo-client-post-2',
      title: 'Upcoming onboarding wave',
      status: 'scheduled',
      visibility: 'connections',
      scheduledAt: '2024-04-18T15:00:00Z',
      publishedAt: null,
    },
    createdAt: '2024-04-15T07:45:00Z',
    updatedAt: '2024-04-15T07:45:00Z',
  },
];

const USER_FALLBACK_ANALYTICS = computeTimelineAnalyticsFromClient(
  USER_FALLBACK_POSTS,
  USER_FALLBACK_ENTRIES,
);

export default function useUserTimeline({ userId, enabled = true } = {}) {
  return useFreelancerTimeline({
    freelancerId: userId,
    enabled,
    resourceKeyPrefix: 'user:timeline',
    demoOwnerId: 'demo-user',
    fallbackWorkspace: USER_FALLBACK_WORKSPACE,
    fallbackPosts: USER_FALLBACK_POSTS,
    fallbackEntries: USER_FALLBACK_ENTRIES,
    fallbackAnalytics: USER_FALLBACK_ANALYTICS,
    services: {
      fetchWorkspace: fetchUserTimelineWorkspace,
      updateSettings: updateUserTimelineSettings,
      createEntry: createUserTimelineEntry,
      updateEntry: updateUserTimelineEntry,
      deleteEntry: deleteUserTimelineEntry,
      createPost: createUserTimelinePost,
      updatePost: updateUserTimelinePost,
      deletePost: deleteUserTimelinePost,
      publishPost: publishUserTimelinePost,
      recordMetrics: recordUserTimelinePostMetrics,
    },
  });
}
