name: gigvora_design_system
description: "Gigvora design system primitives, design token loaders, and theme builders."
version: 0.1.0
publish_to: "none"

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  collection: ^1.18.0
  gigvora_foundation:
    path: ../gigvora_foundation

flutter:
  assets:
    - assets/tokens/
