import {
  ArrowTrendingUpIcon,
  BanknotesIcon,
  BoltIcon,
  BriefcaseIcon,
  CalendarDaysIcon,
  ChatBubbleBottomCenterTextIcon,
  ChartBarSquareIcon,
  ClipboardDocumentCheckIcon,
  DocumentTextIcon,
  Cog6ToothIcon,
  LockClosedIcon,
  InboxStackIcon,
  FolderIcon,
  HeartIcon,
  HomeModernIcon,
  LifebuoyIcon,
  MegaphoneIcon,
  PhotoIcon,
  RectangleStackIcon,
  ShieldCheckIcon,
  SparklesIcon,
  Squares2X2Icon,
  StarIcon,
  UserCircleIcon,
  UserGroupIcon,
  ScaleIcon,
} from '@heroicons/react/24/outline';

export const MENU_GROUPS = [
  {
    id: 'core',
    label: 'Core',
    items: [
      { id: 'profile-overview', name: 'Profile', description: 'Signals & context', icon: UserCircleIcon },
      { id: 'operations-hq', name: 'Ops', description: 'Workspace HQ', icon: HomeModernIcon },
      { id: 'delivery-ops', name: 'Delivery', description: 'Orders & SLAs', icon: ClipboardDocumentCheckIcon },
      { id: 'task-management', name: 'Tasks', description: 'Boards & sprints', icon: Squares2X2Icon },
      {
        id: 'planning',
        name: 'Planner',
        description: 'Schedule & rituals',
        icon: CalendarDaysIcon,
        href: '/dashboard/freelancer/planner',
      },
      { id: 'mentoring', name: 'Mentoring', description: 'Sessions & mentors', icon: ChartBarSquareIcon },
      {
        id: 'volunteering-management',
        name: 'Volunteer',
        description: 'Keep volunteer work organised.',
        icon: HeartIcon,
        href: '/dashboard/freelancer/volunteer',
      },
      {
        id: 'inbox',
        name: 'Inbox & communications',
        description: 'Messages, saved replies, routing rules, and support cases.',
        icon: InboxStackIcon,
      },
    ],
  },
  {
    id: 'projects',
    label: 'Projects',
    items: [
      { id: 'project-excellence', name: 'Excellence', description: 'Project quality', icon: ClipboardDocumentCheckIcon },
      { id: 'project-lab', name: 'Lab', description: 'Workflow lab', icon: BriefcaseIcon },
      { id: 'timeline-management', name: 'Timeline', description: 'Content & updates', icon: SparklesIcon },
    ],
  },
  {
    id: 'commerce',
    label: 'Commerce',
    items: [
      { id: 'gig-studio', name: 'Studio', description: 'Build offerings', icon: SparklesIcon },
      { id: 'gig-marketplace', name: 'Marketplace', description: 'Listings & demand', icon: MegaphoneIcon },
      { id: 'automation', name: 'Signals', description: 'Automation', icon: BoltIcon },
      {
        id: 'creation-studio',
        name: 'Creation',
        description: 'Content studio',
        href: '/dashboard/freelancer/creation-studio',
        icon: PhotoIcon,
      },
    ],
  },
  {
    id: 'finance',
    label: 'Finance & safety',
    items: [
      { id: 'finance', name: 'Cashflow', description: 'Money & trust', icon: BanknotesIcon },
      { id: 'wallet', name: 'Wallet', description: 'Treasury & automation', icon: BanknotesIcon },
      {
        id: 'escrow-management',
        name: 'Escrow',
        description: 'Accounts, releases, disputes',
        icon: LockClosedIcon,
      },
      { id: 'dispute-management', name: 'Disputes', description: 'Resolve issues', icon: ScaleIcon },
      { id: 'workspace-settings', name: 'Settings', description: 'Preferences', icon: Cog6ToothIcon },
      { id: 'id-verification', name: 'Identity', description: 'Verify profile', icon: ShieldCheckIcon },
    ],
  },
  {
    id: 'brand',
    label: 'Brand & growth',
    items: [
      { id: 'profile-showcase', name: 'Showcase', description: 'Portfolio', icon: PhotoIcon },
      { id: 'references', name: 'References', description: 'Testimonials', icon: ChatBubbleBottomCenterTextIcon },
      { id: 'review-management', name: 'Reviews', description: 'Gather feedback', icon: StarIcon },
      {
        id: 'documents',
        name: 'Documents',
        description: 'CVs & cover letters',
        href: '/dashboard/freelancer/documents',
        icon: DocumentTextIcon,
      },
      { id: 'network', name: 'Network', description: 'Community', icon: UserGroupIcon },
      { id: 'growth-partnerships', name: 'Growth', description: 'Pipeline & partnerships', icon: ArrowTrendingUpIcon },
      { id: 'portfolio-management', name: 'Portfolio', description: 'Assets & cases', icon: FolderIcon },
    ],
  },
  {
    id: 'quick',
    label: 'Quick access',
    items: [{ id: 'quick-access', name: 'Shortcuts', description: 'Dashboards', icon: RectangleStackIcon }],
  },
  {
    id: 'support',
    label: 'Support',
    items: [{ id: 'support', name: 'Help', description: 'Support desk', icon: LifebuoyIcon }],
  },
];

export const AVAILABLE_DASHBOARDS = [
  { id: 'freelancer', label: 'Freelancer', href: '/dashboard/freelancer' },
  { id: 'user', label: 'User', href: '/dashboard/user' },
  { id: 'freelancer-pipeline', label: 'Pipeline HQ', href: '/dashboard/freelancer/pipeline' },
  { id: 'freelancer-creation-studio', label: 'Creation studio', href: '/dashboard/freelancer/creation-studio' },
  { id: 'freelancer-networking', label: 'Network', href: '/dashboard/freelancer/networking' },
  { id: 'company', label: 'Company', href: '/dashboard/company' },
];
