name: gigvora_foundation
description: "Shared core utilities, networking, caching, analytics, and dependency injection for the Gigvora Flutter apps."
version: 0.1.0
publish_to: "none"

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  hive_flutter: ^1.1.0
  meta: ^1.12.0
  collection: ^1.18.0
  async: ^2.11.0
  get_it: ^7.6.4
  logging: ^1.2.0
  intl: ^0.19.0
  graphql: ^5.1.3
  web_socket_channel: ^2.4.0
  crypto: ^3.0.3
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
