export const DEFAULT_PROFILE = {
  name: 'Jordan Mentor',
  role: 'Mentor-in-residence',
  headline: 'Product strategy mentor & operator',
  initials: 'JM',
  status: 'Accepting mentees',
  badges: ['Product strategy', 'Leadership pods'],
  metrics: [
    { label: 'Active mentees', value: '12', change: '+2 this month' },
    { label: 'Avg. rating', value: '4.9', change: 'Last 90 days' },
    { label: 'Net promoter', value: '78', change: 'Mentor guild benchmark: 72' },
  ],
  email: 'mentor@gigvora.com',
  timezone: 'GMT',
  focusAreas: ['Leadership sprints', 'Product strategy'],
  bio: 'Former CPO helping product leaders scale rituals, decisions, and teams. 12+ years of shipping category-leading experiences.',
  introVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
  socialLinks: ['https://www.linkedin.com/in/jordan-mentor', 'https://mentor.gigvora.com'],
  sessionFee: { amount: 180, currency: '£' },
  availabilityNotes: 'Tuesday & Thursday afternoons for deep dives, Friday mornings for async reviews.',
  packagesOverview: 'Flagship leadership accelerator and product growth audit programmes available in hybrid formats.',
};

export const DEFAULT_DASHBOARD = {
  stats: {
    activeMentees: 12,
    activeMenteesChange: 8,
    upcomingSessions: 9,
    upcomingSessionsChange: 12,
    avgRating: 4.9,
    avgRatingChange: 1,
    monthlyRevenue: 4200,
    monthlyRevenueChange: 15,
  },
  conversion: [
    { id: 'views', label: 'Explorer profile views', value: 186, delta: 6 },
    { id: 'requests', label: 'Booking requests', value: 38, delta: 9 },
    { id: 'confirmed', label: 'Confirmed sessions', value: 24, delta: 12 },
  ],
  availability: [
    {
      id: 'slot-1',
      day: 'Tuesday',
      start: new Date().setHours(13, 0, 0, 0),
      end: new Date().setHours(14, 0, 0, 0),
      format: '1:1 session',
      capacity: 1,
    },
    {
      id: 'slot-2',
      day: 'Thursday',
      start: new Date().setHours(16, 0, 0, 0),
      end: new Date().setHours(17, 0, 0, 0),
      format: 'Office hours',
      capacity: 6,
    },
  ],
  packages: [
    {
      id: 'pkg-1',
      name: 'Leadership accelerator',
      description: 'Six weeks of strategic rituals, async reviews, and executive storytelling prep.',
      sessions: 6,
      price: 1800,
      currency: '£',
      format: 'Hybrid',
      outcome: 'Promotion narrative & influence plan',
    },
    {
      id: 'pkg-2',
      name: 'Product growth audit',
      description: 'Three deep dives into activation, monetisation, and experiment velocity.',
      sessions: 3,
      price: 720,
      currency: '£',
      format: 'Virtual',
      outcome: '90-day experiment roadmap',
    },
  ],
  bookings: [
    {
      id: 'booking-1',
      mentee: 'Alex Rivera',
      role: 'Director of Product',
      package: 'Leadership accelerator',
      focus: 'Influence & stakeholder mapping',
      scheduledAt: new Date().setDate(new Date().getDate() + 2),
      status: 'Scheduled',
      price: 1800,
      currency: '£',
      paymentStatus: 'Paid',
      channel: 'Explorer',
      segment: 'active',
    },
    {
      id: 'booking-2',
      mentee: 'Linh Tran',
      role: 'Head of Product Marketing',
      package: 'Product growth audit',
      focus: 'Activation storytelling',
      scheduledAt: new Date().setDate(new Date().getDate() + 5),
      status: 'Awaiting pre-work',
      price: 720,
      currency: '£',
      paymentStatus: 'Pending',
      channel: 'Referral',
      segment: 'pending',
    },
  ],
  segments: [
    {
      id: 'active',
      title: 'Confirmed sessions',
      description: 'Mentorship sessions locked in with payment confirmed.',
    },
    {
      id: 'pending',
      title: 'Pending actions',
      description: 'Bookings awaiting payment, materials, or pre-work.',
    },
  ],
  feedback: [
    {
      id: 'feedback-1',
      mentee: 'Priya Desai',
      highlight: 'Unlocked a promotion narrative that resonated with senior leadership.',
      rating: 5,
    },
    {
      id: 'feedback-2',
      mentee: 'Chris Osei',
      highlight: 'Loved the async Loom reviews between sessions – sped up implementation.',
      rating: 5,
    },
  ],
  explorerPlacement: {
    score: 92,
    position: 'Top 3 in leadership mentorship',
    nextActions: ['Add 2 more availability slots', 'Upload testimonial video', 'Promote new async review package'],
  },
  finance: {
    summary: {
      outstandingInvoices: 720,
      paidInvoices: 1800,
      upcomingPayouts: 2100,
      availableBalance: 600,
      monthlyTarget: 6000,
      projected: 5400,
      variance: -600,
    },
    invoices: [
      {
        id: 'invoice-1',
        reference: 'INV-2024-001',
        mentee: 'Alex Rivera',
        package: 'Leadership accelerator',
        amount: 1800,
        currency: '£',
        status: 'Paid',
        issuedOn: new Date().toISOString(),
        dueOn: new Date().toISOString(),
        paidOn: new Date().toISOString(),
        notes: 'Paid via Explorer checkout with corporate card.',
      },
      {
        id: 'invoice-2',
        reference: 'INV-2024-002',
        mentee: 'Linh Tran',
        package: 'Product growth audit',
        amount: 720,
        currency: '£',
        status: 'Sent',
        issuedOn: new Date().toISOString(),
        dueOn: new Date().toISOString(),
        notes: 'Awaiting pre-work upload before payment triggers.',
      },
    ],
    payouts: [
      {
        id: 'payout-1',
        reference: 'PO-2024-004',
        amount: 2100,
        currency: '£',
        status: 'Processing',
        initiatedOn: new Date().toISOString(),
        expectedOn: new Date().toISOString(),
        method: 'Stripe Express',
        destination: 'GB33-STER-1234-9876',
        notes: 'Explorer earnings payout in progress.',
      },
      {
        id: 'payout-2',
        reference: 'PO-2024-003',
        amount: 1200,
        currency: '£',
        status: 'Paid',
        initiatedOn: new Date().toISOString(),
        expectedOn: new Date().toISOString(),
        paidOn: new Date().toISOString(),
        method: 'Stripe Express',
        destination: 'GB33-STER-1234-9876',
      },
    ],
    revenueStreams: [
      { id: 'one-on-one', label: '1:1 Coaching', amount: 3200, currency: '£', change: 12 },
      { id: 'cohorts', label: 'Cohort clinics', amount: 1400, currency: '£', change: 8 },
      { id: 'async', label: 'Async reviews', amount: 800, currency: '£', change: 17 },
    ],
  },
};
