import { Router } from 'express';
import authRoutes from './authRoutes.js';
import userRoutes from './userRoutes.js';
import freelancerRoutes from './freelancerRoutes.js';
import feedRoutes from './feedRoutes.js';
import searchRoutes from './searchRoutes.js';
import discoveryRoutes from './discoveryRoutes.js';
import analyticsRoutes from './analyticsRoutes.js';
import messagingRoutes from './messagingRoutes.js';
import trustRoutes from './trustRoutes.js';
import autoAssignRoutes from './autoAssignRoutes.js';
import projectRoutes from './projectRoutes.js';
import launchpadRoutes from './launchpadRoutes.js';
import headhunterRoutes from './headhunterRoutes.js';
import adminRoutes from './adminRoutes.js';
import workManagementRoutes from './workManagementRoutes.js';
import financeRoutes from './financeRoutes.js';
import freelancerRoutes from './freelancerRoutes.js';
import clientPortalRoutes from './clientPortalRoutes.js';
import learningHubRoutes from './learningHubRoutes.js';
import workspaceTemplateRoutes from './workspaceTemplateRoutes.js';
import companyRoutes from './companyRoutes.js';

const router = Router();

router.use('/auth', authRoutes);
router.use('/freelancers', freelancerRoutes);
router.use('/users', userRoutes);
router.use('/feed', feedRoutes);
router.use('/search', searchRoutes);
router.use('/discovery', discoveryRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/messaging', messagingRoutes);
router.use('/trust', trustRoutes);
router.use('/auto-assign', autoAssignRoutes);
router.use('/projects/:projectId/work-management', workManagementRoutes);
router.use('/projects', projectRoutes);
router.use('/launchpad', launchpadRoutes);
router.use('/headhunter', headhunterRoutes);
router.use('/admin', adminRoutes);
router.use('/finance', financeRoutes);
router.use('/freelancers', freelancerRoutes);
router.use('/freelancer', freelancerRoutes);
router.use('/client-portals', clientPortalRoutes);
router.use('/learning-hub', learningHubRoutes);
router.use('/workspace-templates', workspaceTemplateRoutes);
router.use('/company', companyRoutes);

export default router;
