import { Router } from 'express';

import adRoutes from './adRoutes.js';
import adminRoutes from './adminRoutes.js';
import agencyRoutes from './agencyRoutes.js';
import agencyJobManagementRoutes from './agencyJobManagementRoutes.js';
import agencyBlogRoutes from './agencyBlogRoutes.js';
import agencyWalletRoutes from './agencyWalletRoutes.js';
import analyticsRoutes from './analyticsRoutes.js';
import authRoutes from './authRoutes.js';
import autoAssignRoutes from './autoAssignRoutes.js';
import blogAdminRoutes from './blogAdminRoutes.js';
import blogRoutes from './blogRoutes.js';
import clientPortalRoutes from './clientPortalRoutes.js';
import collaborationRoutes from './collaborationRoutes.js';
import companyRoutes from './companyRoutes.js';
import complianceRoutes from './complianceRoutes.js';
import connectionRoutes from './connectionRoutes.js';
import creationStudioRoutes from './creationStudioRoutes.js';
import deliverableVaultRoutes from './deliverableVaultRoutes.js';
import discoveryRoutes from './discoveryRoutes.js';
import feedRoutes from './feedRoutes.js';
import financeRoutes from './financeRoutes.js';
import freelancerRoutes from './freelancerRoutes.js';
import domainRoutes from './domainRoutes.js';
import groupRoutes from './groupRoutes.js';
import headhunterRoutes from './headhunterRoutes.js';
import interviewRoutes from './interviewRoutes.js';
import launchpadRoutes from './launchpadRoutes.js';
import learningHubRoutes from './learningHubRoutes.js';
import mentorshipRoutes from './mentorshipRoutes.js';
import messagingRoutes from './messagingRoutes.js';
import networkingRoutes from './networkingRoutes.js';
import pipelineRoutes from './pipelineRoutes.js';
import projectGigManagementRoutes from './projectGigManagementRoutes.js';
import projectWorkspaceRoutes from './projectWorkspaceRoutes.js';
import projectRoutes from './projectRoutes.js';
import reputationRoutes from './reputationRoutes.js';
import searchRoutes from './searchRoutes.js';
import trustRoutes from './trustRoutes.js';
import userRoutes from './userRoutes.js';
import userMentoringRoutes from './userMentoringRoutes.js';
import workspaceTemplateRoutes from './workspaceTemplateRoutes.js';
import workManagementRoutes from './workManagementRoutes.js';
import runtimeRoutes from './runtimeRoutes.js';
import docsRoutes from './docsRoutes.js';
import eventManagementRoutes from './eventManagementRoutes.js';

const router = Router();

router.use('/ads', adRoutes);
router.use('/admin', adminRoutes);
router.use('/admin/blog', blogAdminRoutes);
router.use('/agency/job-management', agencyJobManagementRoutes);
router.use('/agency/wallet', agencyWalletRoutes);
router.use('/agency', agencyRoutes);
router.use('/agency/blog', agencyBlogRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/auth', authRoutes);
router.use('/auto-assign', autoAssignRoutes);
router.use('/blog', blogRoutes);
router.use('/client-portals', clientPortalRoutes);
router.use('/collaboration', collaborationRoutes);
router.use('/company', companyRoutes);
router.use('/compliance', complianceRoutes);
router.use('/connections', connectionRoutes);
router.use('/creation-studio', creationStudioRoutes);
router.use('/deliverable-vault', deliverableVaultRoutes);
router.use('/discovery', discoveryRoutes);
router.use('/domains', domainRoutes);
router.use('/feed', feedRoutes);
router.use('/finance', financeRoutes);
router.use('/freelancer', freelancerRoutes);
router.use('/freelancers', freelancerRoutes);
router.use('/groups', groupRoutes);
router.use('/headhunter', headhunterRoutes);
router.use('/interviews', interviewRoutes);
router.use('/launchpad', launchpadRoutes);
router.use('/learning-hub', learningHubRoutes);
router.use('/mentors', mentorshipRoutes);
router.use('/messaging', messagingRoutes);
router.use('/networking', networkingRoutes);
router.use('/pipeline', pipelineRoutes);
router.use('/projects', projectRoutes);
router.use('/projects/:projectId/work-management', workManagementRoutes);
router.use('/reputation', reputationRoutes);
router.use('/search', searchRoutes);
router.use('/trust', trustRoutes);
router.use('/users', userRoutes);
router.use('/users/:userId/mentoring', userMentoringRoutes);
router.use('/users/:userId/project-gig-management', projectGigManagementRoutes);
router.use('/users/:userId/project-workspace', projectWorkspaceRoutes);
router.use('/users/:userId/events', eventManagementRoutes);
router.use('/workspace-templates', workspaceTemplateRoutes);
router.use('/runtime', runtimeRoutes);
router.use('/docs', docsRoutes);

export default router;
